name: Tests
on:
  - push
  - pull_request
jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Create makefile
        run: perl Makefile.PL
      - name: Run tests
        run: make test
  test:
    name: ${{ matrix.os }}, perl ${{ matrix.perl }}
    needs: smoketest
    strategy:
      matrix:
        os: ['ubuntu', 'macos', 'windows']
        perl: ['5.8', '5.10', '5.12', '5.14', '5.16', '5.18', '5.20', '5.22', '5.24', '5.26', '5.28', '5.30', '5.32', '5.34', '5.36']
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Create makefile
        run: perl Makefile.PL
      - name: Run tests
        run: make test
